// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupervisorBravo.Persistence;

#nullable disable

namespace SupervisorBravo.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504141311_Anadir dixell")]
    partial class Anadirdixell
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MoodbusId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SetPoint")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DixellBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Temperatures.Temperature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DixellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TemperatureMeasurement")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DixellId");

                    b.ToTable("Temperature", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXR60CX", b =>
                {
                    b.HasBaseType("SupervisorBravo.Domain.Entities.Dixell.DixellBase");

                    b.Property<bool>("ControlON_OFF")
                        .HasColumnType("bit");

                    b.Property<bool>("Thawing")
                        .HasColumnType("bit");

                    b.ToTable("DixellXR60CX", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXT111C", b =>
                {
                    b.HasBaseType("SupervisorBravo.Domain.Entities.Dixell.DixellBase");

                    b.Property<bool>("ControlON_OFF")
                        .HasColumnType("bit");

                    b.ToTable("DixellXT111C", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Temperatures.Temperature", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", "Dixell")
                        .WithMany("temperatures")
                        .HasForeignKey("DixellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dixell");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXR60CX", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", null)
                        .WithOne()
                        .HasForeignKey("SupervisorBravo.Domain.Entities.Dixell.DixellXR60CX", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXT111C", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", null)
                        .WithOne()
                        .HasForeignKey("SupervisorBravo.Domain.Entities.Dixell.DixellXT111C", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellBase", b =>
                {
                    b.Navigation("temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
