// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupervisorBravo.Persistence;

#nullable disable

namespace SupervisorBravo.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250814150941_AnalogVariableScaleFactor")]
    partial class AnalogVariableScaleFactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalogMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MeasurementValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PLCAnalogVariableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PLCAnalogVariableId");

                    b.ToTable("AnalogMeasurements");
                });

            modelBuilder.Entity("DigitalMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MeasurementValue")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PLCDigitalVariableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PLCDigitalVariableId");

                    b.ToTable("DigitalMeasurements");
                });

            modelBuilder.Entity("PLCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<byte>("ModbusId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PLCDevices");
                });

            modelBuilder.Entity("PLCVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Address")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsWritable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PLCDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PLCDeviceId");

                    b.ToTable("PLCVariable");

                    b.HasDiscriminator().HasValue("PLCVariable");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlarmEnable")
                        .HasColumnType("boolean");

                    b.Property<bool>("ControlON_OFF")
                        .HasColumnType("boolean");

                    b.Property<bool>("ControlON_OFFWrite")
                        .HasColumnType("boolean");

                    b.Property<int>("MoodbusId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SetPoint")
                        .HasColumnType("double precision");

                    b.Property<bool>("SetPointWrite")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DixellBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Schedule.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Recurrence")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<DayOfWeek>>("RecurringDays")
                        .HasColumnType("jsonb");

                    b.Property<string>("RecurringDaysSerialized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RecurringDays");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SetPointValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ScheduledTask", null, t =>
                        {
                            t.Property("RecurringDays")
                                .HasColumnName("RecurringDays1");
                        });
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Schedule.ScheduledTaskExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("ScheduledTaskExecutionLogs");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.System.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlarmDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alarm", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.System.DeviceAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlarmDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeviceAlarm", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Temperatures.Temperature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ControlEnable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CoolingMeasurement")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DefrostMeasurement")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisconnectDixell")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DixellId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ElectroValveMeasurement")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("On_OffDixell")
                        .HasColumnType("boolean");

                    b.Property<double>("SetPointMeasurement")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMeasurement")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DixellId");

                    b.ToTable("Temperature", (string)null);
                });

            modelBuilder.Entity("PLCAnalogVariable", b =>
                {
                    b.HasBaseType("PLCVariable");

                    b.Property<double>("ScaleFactor")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("PLCAnalogVariable");
                });

            modelBuilder.Entity("PLCDigitalVariable", b =>
                {
                    b.HasBaseType("PLCVariable");

                    b.Property<int>("BitIndex")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("PLCDigitalVariable");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXR", b =>
                {
                    b.HasBaseType("SupervisorBravo.Domain.Entities.Dixell.DixellBase");

                    b.Property<bool>("Cooling")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fan")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thawing")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThawingWrite")
                        .HasColumnType("boolean");

                    b.Property<string>("modelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("DixellXR", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXT", b =>
                {
                    b.HasBaseType("SupervisorBravo.Domain.Entities.Dixell.DixellBase");

                    b.Property<bool>("ElectroValve")
                        .HasColumnType("boolean");

                    b.ToTable("DixellXT", (string)null);
                });

            modelBuilder.Entity("AnalogMeasurement", b =>
                {
                    b.HasOne("PLCAnalogVariable", "PLCAnalogVariable")
                        .WithMany("Measurements")
                        .HasForeignKey("PLCAnalogVariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLCAnalogVariable");
                });

            modelBuilder.Entity("DigitalMeasurement", b =>
                {
                    b.HasOne("PLCDigitalVariable", "PLCDigitalVariable")
                        .WithMany("Measurements")
                        .HasForeignKey("PLCDigitalVariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLCDigitalVariable");
                });

            modelBuilder.Entity("PLCVariable", b =>
                {
                    b.HasOne("PLCDevice", "PLCDevice")
                        .WithMany("Variables")
                        .HasForeignKey("PLCDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLCDevice");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Schedule.ScheduledTask", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Schedule.ScheduledTaskExecutionLog", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Schedule.ScheduledTask", "Task")
                        .WithMany("ExecutionLog")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Temperatures.Temperature", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", "Dixell")
                        .WithMany("temperatures")
                        .HasForeignKey("DixellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dixell");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXR", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", null)
                        .WithOne()
                        .HasForeignKey("SupervisorBravo.Domain.Entities.Dixell.DixellXR", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXT", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", null)
                        .WithOne()
                        .HasForeignKey("SupervisorBravo.Domain.Entities.Dixell.DixellXT", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PLCDevice", b =>
                {
                    b.Navigation("Variables");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellBase", b =>
                {
                    b.Navigation("temperatures");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Schedule.ScheduledTask", b =>
                {
                    b.Navigation("ExecutionLog");
                });

            modelBuilder.Entity("PLCAnalogVariable", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("PLCDigitalVariable", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
