// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupervisorBravo.Persistence;

#nullable disable

namespace SupervisorBravo.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AlarmEnable")
                        .HasColumnType("boolean");

                    b.Property<bool>("ControlON_OFF")
                        .HasColumnType("boolean");

                    b.Property<bool>("ControlON_OFFWrite")
                        .HasColumnType("boolean");

                    b.Property<int>("MoodbusId")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SetPoint")
                        .HasColumnType("double precision");

                    b.Property<bool>("SetPointWrite")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DixellBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.System.Alarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlarmDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alarm", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.System.DeviceAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AlarmDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeviceAlarm", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Temperatures.Temperature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ControlEnable")
                        .HasColumnType("boolean");

                    b.Property<bool>("DisconnectDixell")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DixellId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MeasurementTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("On_OffDixell")
                        .HasColumnType("boolean");

                    b.Property<double>("TemperatureMeasurement")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DixellId");

                    b.ToTable("Temperature", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXR", b =>
                {
                    b.HasBaseType("SupervisorBravo.Domain.Entities.Dixell.DixellBase");

                    b.Property<bool>("Cooling")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fan")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thawing")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThawingWrite")
                        .HasColumnType("boolean");

                    b.ToTable("DixellXR", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXT", b =>
                {
                    b.HasBaseType("SupervisorBravo.Domain.Entities.Dixell.DixellBase");

                    b.Property<bool>("ElectroValve")
                        .HasColumnType("boolean");

                    b.ToTable("DixellXT", (string)null);
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Temperatures.Temperature", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", "Dixell")
                        .WithMany("temperatures")
                        .HasForeignKey("DixellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dixell");
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXR", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", null)
                        .WithOne()
                        .HasForeignKey("SupervisorBravo.Domain.Entities.Dixell.DixellXR", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellXT", b =>
                {
                    b.HasOne("SupervisorBravo.Domain.Entities.Dixell.DixellBase", null)
                        .WithOne()
                        .HasForeignKey("SupervisorBravo.Domain.Entities.Dixell.DixellXT", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupervisorBravo.Domain.Entities.Dixell.DixellBase", b =>
                {
                    b.Navigation("temperatures");
                });
#pragma warning restore 612, 618
        }
    }
}
